export const Districts = [
  {
    Kasargod: [
      "Ajanur",
      "Badiadka",
      "Balal",
      "Bedadka",
      "Belloor",
      "Chemnad",
      "Chengala",
      "Cheruvathur",
      "Delampady",
      "East Eleri",
      "Enmakaje",
      "Kallar",
      "Karadka",
      "Kayyur Cheemeni",
      "Kinanoor - Karinthalam",
      "KodomBelur",
      "Kumbadaje",
      "Kumbla",
      "Kuttikol",
      "Madhur",
      "Madikai",
      "Mangalpady",
      "Manjeshwar",
      "Meenja",
      "MogralPuthur",
      "Muliyar",
      "Padne",
      "Paivalike",
      "Pallikere",
      "Panathady",
    ],
  },
  {
    Kannur: [
      "Alakode",
      "Anjarakandy",
      "Aralam",
      "Ayyankunnu",
      "Azhikode",
      "Chapparapadava",
      "Chembilode",
      "Chengalayi",
      "Cherukunnu",
      "Cherupuzha",
      "Cheruthazham",
      "Chirakkal",
      "Chittariparamba",
      "Chokli",
      "Dharmadam",
      "Eramam Kuttur",
      "Eranholi",
      "Eruvessy",
      "Ezhome",
      "Irikkur",
      "Kadambur",
      "Kadannappally Panapuzha",
      "Kadirur",
      "Kalliasseri",
      "Kanichar",
      "Kankol - Alappadamba",
      "Kannapuram",
      "Karivellur Peralam",
      "Keezhallur",
      "Kelakam",
      "Kolachery",
      "Kolayad",
      "Koodali",
      "Kottayam",
      "Kottiyoor",
      "Kunhimangalam",
      "Kunnothuparamba",
      "Kurumathur",
      "Kuttiattoor",
      "Madayi",
      "Malappattam",
      "Malur",
      "Mangattidam",
      "Mattool",
      "Mayyil",
      "Mokeri",
      "Munderi",
      "Muzhakkunnu",
      "Muzhappilangad",
      "Naduvil",
      "Narath",
      "New Mahe",
      "Padiyoor",
      "Panniyannur",
      "Pappinisseri",
      "Pariyaram",
      "Pattiam",
      "Pattuvam",
      "Payam",
      "Payyavoor",
      "Peralassery",
      "Peravoor",
      "Peringome Vayakkara",
      "Pinarayi",
      "Ramanthali",
      "Thillankery",
      "Triprangottoor",
      "Udayagiri",
      "Ulikkal",
      "Valapattanam",
      "Vengad",
    ],
  },
];
